# Generated by Django 5.1.1 on 2024-09-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_sociallink_icon_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='icon_url',
            new_name='icon_url_social',
        ),
    ]
