# Generated by Django 5.1.1 on 2024-09-14 20:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_rename_icon_url_sociallink_icon_url_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(verbose_name='Biografia'),
        ),
    ]
